// Complete papers data extracted from LaTeX table - All research papers
const papersData = [
  // Finance Domain (9 papers)
  {
    domain: "Finance",
    author: "Nakagawa et al. (2019)",
    year: "2019",
    task: "REG",
    mlModel: "LSTM",
    xaiMethod: "LRP",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local",
    metrics: "Nil",
    problemType: "RS, DS, BS",
    mlStage: "Training",
    dataset: "TOPIX500 (Japanese Stock Market)",
    inputType: "Num",
    outputType: "Num"
  },
  {
    domain: "Finance",
    author: "Sachan et al. (2020)",
    year: "2019",
    task: "CLS",
    mlModel: "Gradient Boosting Trees",
    xaiMethod: "Belief Rule Base",
    xaiCategory: "RB",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local/Global",
    metrics: "Accuracy, Stability",
    problemType: "RM, FD",
    mlStage: "Training",
    dataset: "Financial Conduct Authority (FCA) Dataset",
    inputType: "Num",
    outputType: "Num"
  },
  {
    domain: "Finance",
    author: "Bowden et al. (2024)",
    year: "2020",
    task: "CLF",
    mlModel: "Gradient Boosting",
    xaiMethod: "Shapley Values, PDP",
    xaiCategory: "FA, VB",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local",
    metrics: "AUC",
    problemType: "PM, RM",
    mlStage: "Training, Monitoring",
    dataset: "1000 German Banking Customer",
    inputType: "Num",
    outputType: "Num"
  },
  {
    domain: "Finance",
    author: "Bussmann et al. (2021)",
    year: "2021",
    task: "CLS",
    mlModel: "XGBoost",
    xaiMethod: "TreeSHAP",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local",
    metrics: "ROC",
    problemType: "PM",
    mlStage: "Evaluation",
    dataset: "Credit scoring for SME Companies in Southern Europe",
    inputType: "Num",
    outputType: "Bin"
  },
  {
    domain: "Finance",
    author: "Gramegna and Giudici (2020)",
    year: "2020",
    task: "CLS",
    mlModel: "XGBoost",
    xaiMethod: "TreeSHAP",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local",
    metrics: "AUC",
    problemType: "RM, DS, BS",
    mlStage: "Training, Evaluation",
    dataset: "Non-life insurance Neosurance Italy-Based Insurance Company",
    inputType: "Num",
    outputType: "Cat"
  },
  {
    domain: "Finance",
    author: "Gite et al. (2021)",
    year: "2021",
    task: "CLS",
    mlModel: "LSTM-CNN",
    xaiMethod: "LIME",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local",
    metrics: "Accuracy",
    problemType: "DS, BS",
    mlStage: "Training",
    dataset: "Indian Financial News Headlines Dataset Pulse, Yahoo Finance dataset",
    inputType: "Txt",
    outputType: "Num"
  },
  {
    domain: "Finance",
    author: "Nguyen and Truong (2024)",
    year: "2024",
    task: "CLS",
    mlModel: "Random Forest",
    xaiMethod: "LIME",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local",
    metrics: "Gini, AUC",
    problemType: "RM, DS, CR",
    mlStage: "Training",
    dataset: "German Credit scoring, Taiwan Default Payment",
    inputType: "Tab",
    outputType: "Bin"
  },
  {
    domain: "Finance",
    author: "Sathe and Mahalle (2023)",
    year: "2023",
    task: "CLS",
    mlModel: "Random Forest",
    xaiMethod: "LIME, SHAPASH",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local",
    metrics: "Nil",
    problemType: "PM",
    mlStage: "Training",
    dataset: "Kaggle",
    inputType: "Tab",
    outputType: "Bin"
  },
  {
    domain: "Finance",
    author: "Yu et al. (2023)",
    year: "2023",
    task: "NLP",
    mlModel: "GPT-4, Open LLaMA",
    xaiMethod: "Chain-of-Thoughts, Instruction-based Fine-Tuning",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local/Global",
    metrics: "Precision",
    problemType: "RM, BS",
    mlStage: "Training",
    dataset: "5Y NASDAQ-100 Stock Price weekly and Monthly, Company Metadata, historical economic Financial News",
    inputType: "Num, Tex",
    outputType: "Num"
  },

  // Healthcare Domain (9 papers)
  {
    domain: "Healthcare",
    author: "Chereda et al. (2024)",
    year: "2024",
    task: "MCLS",
    mlModel: "GCNN, MLP, Random Forest",
    xaiMethod: "SHAP, LRP",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local/Global",
    metrics: "Stability, F1-Score, Accuracy",
    problemType: "SD, HDT, DS",
    mlStage: "Evaluation",
    dataset: "TCGA Breast Cancer Gene Expression Dataset, HPRD PPI Network",
    inputType: "Num",
    outputType: "Cat"
  },
  {
    domain: "Healthcare",
    author: "Chittajallu et al. (2019)",
    year: "2019",
    task: "CLS",
    mlModel: "Resnet50",
    xaiMethod: "Saliency-map",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local",
    metrics: "Nil",
    problemType: "PM",
    mlStage: "Optimize",
    dataset: "Cholec80",
    inputType: "Img",
    outputType: "Bin"
  },
  {
    domain: "Healthcare",
    author: "Hossain et al. (2020)",
    year: "2020",
    task: "CLS",
    mlModel: "Resnet50",
    xaiMethod: "Grad-CAM",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local",
    metrics: "Nil",
    problemType: "PM",
    mlStage: "Training",
    dataset: "COVID-19",
    inputType: "IMG",
    outputType: "Bin"
  },
  {
    domain: "Healthcare",
    author: "Monroe et al. (2021)",
    year: "2021",
    task: "CLS",
    mlModel: "ResNet50",
    xaiMethod: "Grad-CAM, HihO, RISE",
    xaiCategory: "FA, VB",
    timing: "Post-hoc",
    scope: "Specific",
    level: "Local,Global",
    metrics: "Nil",
    problemType: "PM",
    mlStage: "Evaluation",
    dataset: "PPMI (Parkinson's Progression Markers Initiative)",
    inputType: "IMG",
    outputType: "Cat"
  },
  {
    domain: "Healthcare",
    author: "Hatwell et al. (2020)",
    year: "2020",
    task: "CLS",
    mlModel: "Adaboost",
    xaiMethod: "Classification Rule",
    xaiCategory: "RB",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Global",
    metrics: "Nil",
    problemType: "PM",
    mlStage: "Monitor",
    dataset: "Breast Cancer, Thyroid, Hospital readmission, Understanding Society, Diabetic Retinopathy, Cleveland heart, Cardiotocography mental health survey 16, Mental Health survey 14",
    inputType: "Tab",
    outputType: "Rules"
  },
  {
    domain: "Healthcare",
    author: "Dave et al. (2020)",
    year: "2020",
    task: "CLS",
    mlModel: "XGBoost",
    xaiMethod: "LIME, SHAP, Anchors, Prototype, Contrastive, IG",
    xaiCategory: "FA, EB, SXAI, RB, CB, VB",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local",
    metrics: "Nil",
    problemType: "PM",
    mlStage: "Deploy",
    dataset: "Heart Disease Dataset UCI Repo",
    inputType: "Num",
    outputType: "Num"
  },
  {
    domain: "Healthcare",
    author: "Khodabandehloo et al. (2021)",
    year: "2021",
    task: "REG",
    mlModel: "Decision Tree",
    xaiMethod: "NLP (Template Based)",
    xaiCategory: "RB, CXAI",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local",
    metrics: "Nil",
    problemType: "BA",
    mlStage: "Deploy",
    dataset: "Real-world acquired data including persons with MCI and PwD",
    inputType: "Num",
    outputType: "Num"
  },
  {
    domain: "Healthcare",
    author: "Vasquez-Morales et al. (2019)",
    year: "2022",
    task: "CLS",
    mlModel: "NN",
    xaiMethod: "CBR",
    xaiCategory: "EB, CB",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local",
    metrics: "Nil",
    problemType: "PM",
    mlStage: "Training",
    dataset: "Database of the Colombian Ministry of Health and Social Protection",
    inputType: "Num",
    outputType: "Num"
  },
  {
    domain: "Healthcare",
    author: "Weitz et al. (2019)",
    year: "2019",
    task: "CLS",
    mlModel: "CNN",
    xaiMethod: "LRP, LIME",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local",
    metrics: "Nil",
    problemType: "PM",
    mlStage: "Training",
    dataset: "UNBC-McMaster shoulder pain expression archive, Actorstudy dataset",
    inputType: "IMG",
    outputType: "IMG"
  },

  // Industry 4.0 Domain (6 papers)
  {
    domain: "Industry 4.0",
    author: "Oyekanlu et al. (2018)",
    year: "2018",
    task: "CLS",
    mlModel: "LSTM",
    xaiMethod: "Real-Time Adaptive Wavelet Graphs",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Specific",
    level: "Local",
    metrics: "Accuracy",
    problemType: "PM",
    mlStage: "Training",
    dataset: "IIoT Network Edge Dataset",
    inputType: "Num",
    outputType: "Num"
  },
  {
    domain: "Industry 4.0",
    author: "Rehsa et al. (2019)",
    year: "2019",
    task: "CLS",
    mlModel: "LSTM-RNN",
    xaiMethod: "Saliency Map",
    xaiCategory: "FA, VB",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local",
    metrics: "Recall, Stability",
    problemType: "AS",
    mlStage: "Training",
    dataset: "DFKI-Smart Lego Factory",
    inputType: "Num",
    outputType: "Num"
  },
  {
    domain: "Industry 4.0",
    author: "Terziyan and Vitko (2022)",
    year: "2022",
    task: "CLS",
    mlModel: "NN, decision Tree",
    xaiMethod: "Rule List",
    xaiCategory: "RB",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local",
    metrics: "Nil",
    problemType: "DS",
    mlStage: "Training",
    dataset: "Smart Manufacturing Dataset",
    inputType: "Num",
    outputType: "Bin"
  },
  {
    domain: "Industry 4.0",
    author: "Sun et al. (2020)",
    year: "2020",
    task: "ANOM",
    mlModel: "Random Forest",
    xaiMethod: "SHAP",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local",
    metrics: "Accuracy, Precision",
    problemType: "DS",
    mlStage: "Feature",
    dataset: "Simulated Manufacturing Dataset",
    inputType: "Num",
    outputType: "Cat"
  },
  {
    domain: "Industry 4.0",
    author: "Liu et al. (2021)",
    year: "2021",
    task: "CLS",
    mlModel: "Gradient Boosting",
    xaiMethod: "LIME",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local",
    metrics: "F1-Score, Stability",
    problemType: "PM",
    mlStage: "Deploy",
    dataset: "IoT Sensor Data",
    inputType: "Num",
    outputType: "Num"
  },
  {
    domain: "Industry 4.0",
    author: "Radanliev et al. (2022)",
    year: "2022",
    task: "ANOM",
    mlModel: "Transformer",
    xaiMethod: "Attention Mechanisms",
    xaiCategory: "SE-AI",
    timing: "Intrinsic",
    scope: "Specific",
    level: "Global",
    metrics: "Usability Metrics",
    problemType: "AS",
    mlStage: "Training",
    dataset: "Simulated Digital Twin Data",
    inputType: "Num",
    outputType: "Cat"
  },

  // Aviation Domain (3 papers)
  {
    domain: "Aviation",
    author: "Wang et al. (2021)",
    year: "2022",
    task: "CLS",
    mlModel: "Temporal Fusion Transformer (TFT)",
    xaiMethod: "Not specified",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local",
    metrics: "Not specified",
    problemType: "PM",
    mlStage: "Training",
    dataset: "Flight Data Analysis",
    inputType: "Num, IMG",
    outputType: "Cat"
  },
  {
    domain: "Aviation",
    author: "Saraf et al. (2020)",
    year: "2021",
    task: "CLS",
    mlModel: "DNN",
    xaiMethod: "Not specified",
    xaiCategory: "Not specified",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Global",
    metrics: "Not specified",
    problemType: "Not specified",
    mlStage: "Develop",
    dataset: "Flight Safety Monitoring",
    inputType: "Num",
    outputType: "Cat"
  },
  {
    domain: "Aviation",
    author: "Sutthithatip et al. (2021)",
    year: "2021",
    task: "DS",
    mlModel: "NN",
    xaiMethod: "SHAP, LIME",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local/Global",
    metrics: "Accuracy, Stability",
    problemType: "DS, BS, RM",
    mlStage: "Develop",
    dataset: "Simulated Aircraft Operations Data",
    inputType: "Num",
    outputType: "Cat"
  },

  // Education Domain (7 papers)
  {
    domain: "Education",
    author: "Xie et al. (2021)",
    year: "2020",
    task: "CLS",
    mlModel: "Random Forest",
    xaiMethod: "SHAP",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local",
    metrics: "Accuracy, Stability",
    problemType: "PM, BS, DS, ES",
    mlStage: "Training",
    dataset: "Open University Learning Analytics Dataset",
    inputType: "Num",
    outputType: "Cat"
  },
  {
    domain: "Education",
    author: "Fiok et al. (2022)",
    year: "2021",
    task: "RECM",
    mlModel: "NN",
    xaiMethod: "LIME",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local",
    metrics: "Precision, Recall",
    problemType: "PR, ES",
    mlStage: "Training",
    dataset: "KDD Cup 2010 Dataset",
    inputType: "Num",
    outputType: "Cat"
  },
  {
    domain: "Education",
    author: "Ghosh et al. (2024)",
    year: "2022",
    task: "Predict",
    mlModel: "Gradient Boosting Trees",
    xaiMethod: "SHAP",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local",
    metrics: "F1-Score",
    problemType: "DS, ES",
    mlStage: "Training",
    dataset: "EdNet Dataset",
    inputType: "Num",
    outputType: "Cat"
  },
  {
    domain: "Education",
    author: "Ribeiro et al. (2019)",
    year: "2020",
    task: "REG",
    mlModel: "Logistic Regression",
    xaiMethod: "LIME",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local",
    metrics: "Recall, Precision",
    problemType: "SE",
    mlStage: "Evaluation",
    dataset: "Classroom Engagement Dataset",
    inputType: "Num",
    outputType: "Num"
  },
  {
    domain: "Education",
    author: "Li et al. (2021)",
    year: "2021",
    task: "CLS",
    mlModel: "Decision Tree",
    xaiMethod: "SHAP, Counterfactual Explanations",
    xaiCategory: "FA, EB",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local",
    metrics: "ROC-AUC",
    problemType: "DS",
    mlStage: "Training",
    dataset: "MOOC Dataset",
    inputType: "Num",
    outputType: "Cat"
  },
  {
    domain: "Education",
    author: "Zheng et al. (2024)",
    year: "2022",
    task: "RECM",
    mlModel: "Neural Collaborative Filtering",
    xaiMethod: "Attention Mechanism",
    xaiCategory: "SE-AI",
    timing: "Intrinsic",
    scope: "Specific",
    level: "Local",
    metrics: "Stability, F1-Score",
    problemType: "PM, BS, PR",
    mlStage: "Training",
    dataset: "EdRecSys Dataset",
    inputType: "Num",
    outputType: "Cat"
  },
  {
    domain: "Education",
    author: "Tiukhova et al. (2024)",
    year: "2023",
    task: "CLS",
    mlModel: "BiLSTM",
    xaiMethod: "LIME, SHAP",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local/Global",
    metrics: "Spearman Rank Correlation, Jaccard Similarity",
    problemType: "ES, PM, BS",
    mlStage: "Evaluation",
    dataset: "MOOCs and Flipped Classrooms Dataset (EPFL)",
    inputType: "Num",
    outputType: "Cat"
  },

  // CyberSecurity Domain (8 papers)
  {
    domain: "CyberSecurity",
    author: "Qureshi et al. (2024)",
    year: "2024",
    task: "CLS",
    mlModel: "LightGBM, Decision Trees, Logistic Regression, Neural Networks",
    xaiMethod: "N/A",
    xaiCategory: "N/A",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local/Global",
    metrics: "Not specified",
    problemType: "TD",
    mlStage: "Evaluation",
    dataset: "BoTNeTIoT-L01 Dataset",
    inputType: "Num",
    outputType: "Cat"
  },
  {
    domain: "CyberSecurity",
    author: "Madhu et al. (2023)",
    year: "2023",
    task: "CLS",
    mlModel: "Random Forest, TabNet, CNN, SVM, KNN, GNB, Decision Tree",
    xaiMethod: "Not specified",
    xaiCategory: "Not specified",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local/Global",
    metrics: "Not specified",
    problemType: "TD",
    mlStage: "Evaluation",
    dataset: "Smart Home IoT Dataset, NSL-KDD Dataset",
    inputType: "Num, Cat",
    outputType: "Cat"
  },
  {
    domain: "CyberSecurity",
    author: "Liu et al. (2024)",
    year: "2021",
    task: "ANOM",
    mlModel: "DNN",
    xaiMethod: "Voronoi diagrams",
    xaiCategory: "Not specified",
    timing: "Post-hoc",
    scope: "Not specified",
    level: "Local",
    metrics: "Not specified",
    problemType: "PM, BS, DS",
    mlStage: "Evaluation",
    dataset: "Real-time and simulation data",
    inputType: "Num",
    outputType: "Num"
  },
  {
    domain: "CyberSecurity",
    author: "Sarhan et al. (2022)",
    year: "2021",
    task: "CLS",
    mlModel: "Various classifiers",
    xaiMethod: "SHAP",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local/Global",
    metrics: "Not specified",
    problemType: "RM, PM",
    mlStage: "Evaluation",
    dataset: "IoT security datasets",
    inputType: "Num",
    outputType: "Num"
  },
  {
    domain: "CyberSecurity",
    author: "Le et al. (2023)",
    year: "2020",
    task: "CLS",
    mlModel: "DT, Random Forest",
    xaiMethod: "SHAP",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local",
    metrics: "Not specified",
    problemType: "PM, DS, RM",
    mlStage: "Evaluation",
    dataset: "IoT security system datasets",
    inputType: "Num",
    outputType: "Num"
  },
  {
    domain: "CyberSecurity",
    author: "Rahal et al. (2024)",
    year: "2021",
    task: "CLS",
    mlModel: "kNN, SVM, MLP, tree-based",
    xaiMethod: "LIME, PFI",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local",
    metrics: "Not specified",
    problemType: "CS",
    mlStage: "Evaluation",
    dataset: "IoT botnet attack datasets",
    inputType: "Num, Cat",
    outputType: "Num"
  },
  {
    domain: "CyberSecurity",
    author: "Tabassum et al. (2020)",
    year: "2020",
    task: "ANOM",
    mlModel: "One-Class Classification Algorithms",
    xaiMethod: "Majority Voting",
    xaiCategory: "RB",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local",
    metrics: "Detection Rate",
    problemType: "PM, BS",
    mlStage: "Develop",
    dataset: "IoT and Normal Traffic",
    inputType: "Num",
    outputType: "Num"
  },
  {
    domain: "CyberSecurity",
    author: "Wang et al. (2021)",
    year: "2020",
    task: "CLS",
    mlModel: "Not specified",
    xaiMethod: "SHAP",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local/Global",
    metrics: "Not specified",
    problemType: "PM, RM",
    mlStage: "Evaluation",
    dataset: "IoT network security datasets",
    inputType: "Num",
    outputType: "Num"
  },

  // Social Media Domain (4 papers)
  {
    domain: "Social Media",
    author: "Diwali et al. (2024)",
    year: "2023",
    task: "NLP",
    mlModel: "Random Forest",
    xaiMethod: "SHAP",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local",
    metrics: "Accuracy, Precision",
    problemType: "SP, PM",
    mlStage: "Training",
    dataset: "Twitter Sentiment Analysis Dataset",
    inputType: "Txt",
    outputType: "Num"
  },
  {
    domain: "Social Media",
    author: "Ghosh et al. (2023)",
    year: "2024",
    task: "CLS",
    mlModel: "Gradient Boosting Trees",
    xaiMethod: "LIME, SHAP",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local/Global",
    metrics: "F1-Score",
    problemType: "PM, BS, DS",
    mlStage: "Evaluation",
    dataset: "FakeNewsNet Dataset",
    inputType: "Txt",
    outputType: "Num"
  },
  {
    domain: "Social Media",
    author: "Ribeiro et al. (2016)",
    year: "2022",
    task: "CLS",
    mlModel: "Neural Networks",
    xaiMethod: "Attention Mechanisms",
    xaiCategory: "SE-AI",
    timing: "Intrinsic",
    scope: "Specific",
    level: "Local/Global",
    metrics: "Recall, Stability",
    problemType: "PM, BS, DS",
    mlStage: "Training",
    dataset: "Instagram Influencer Dataset",
    inputType: "Txt",
    outputType: "Cat"
  },
  {
    domain: "Social Media",
    author: "Ibrahimov et al. (2023)",
    year: "2024",
    task: "RECM",
    mlModel: "Collaborative Filtering",
    xaiMethod: "Grad-CAM, SHAP",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Specific",
    level: "Local/Global",
    metrics: "Usability Metrics",
    problemType: "RE, ED",
    mlStage: "Deploy",
    dataset: "YouTube Recommendation Dataset",
    inputType: "Txt",
    outputType: "Num"
  },

  // Genetics Domain (4 papers)
  {
    domain: "Genetics",
    author: "Koo et al. (2018)",
    year: "2018",
    task: "CLF",
    mlModel: "NN",
    xaiMethod: "Saliency Maps",
    xaiCategory: "FA, VB",
    timing: "Post-hoc",
    scope: "Specific",
    level: "Local",
    metrics: "F1-Score",
    problemType: "SD, HDT, DS",
    mlStage: "Evaluation",
    dataset: "DeepBind Dataset",
    inputType: "Seq",
    outputType: "Num"
  },
  {
    domain: "Genetics",
    author: "Chakarborty et al. (2024)",
    year: "2021",
    task: "CLS",
    mlModel: "Random Forest",
    xaiMethod: "SHAP",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local/Global",
    metrics: "Stability, F1-Score",
    problemType: "HDT, DS, RM",
    mlStage: "Training",
    dataset: "dbSNP Dataset",
    inputType: "Num",
    outputType: "Cat"
  },
  {
    domain: "Genetics",
    author: "Meithi et al. (2021)",
    year: "2022",
    task: "CLS",
    mlModel: "Transformer",
    xaiMethod: "Attention Mechanisms",
    xaiCategory: "SE-AI",
    timing: "Intrinsic",
    scope: "Specific",
    level: "Local",
    metrics: "Precision, Recall",
    problemType: "DS, CR, SD",
    mlStage: "Deployment",
    dataset: "1000 Genomes Dataset",
    inputType: "Num",
    outputType: "Seq"
  },
  {
    domain: "Genetics",
    author: "Novielli et al. (2024)",
    year: "2024",
    task: "CLS",
    mlModel: "Random Forest",
    xaiMethod: "SHAP",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local",
    metrics: "Accuracy, Stability",
    problemType: "PM, BS",
    mlStage: "Training",
    dataset: "Beijing PM2.5 Dataset",
    inputType: "Num",
    outputType: "Num"
  },

  // Environment Domain (6 papers)
  {
    domain: "Environment",
    author: "Trofimov et al. (2024)",
    year: "2021",
    task: "CLS",
    mlModel: "Gradient Boosting Trees",
    xaiMethod: "LIME",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local",
    metrics: "Precision, Recall",
    problemType: "PM, RM, DS",
    mlStage: "Evaluation",
    dataset: "USGS Flood Monitoring Dataset",
    inputType: "Num",
    outputType: "Num"
  },
  {
    domain: "Environment",
    author: "Singh et al. (2024)",
    year: "2022",
    task: "CLS",
    mlModel: "Neural Networks",
    xaiMethod: "Attention Mechanisms",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Specific",
    level: "Global",
    metrics: "Stability, Accuracy",
    problemType: "PM, DS, BS",
    mlStage: "Monitoring",
    dataset: "Climate Impact Dataset (CIMP5)",
    inputType: "Num",
    outputType: "Cat"
  },
  {
    domain: "Environment",
    author: "Gholami et al. (2024)",
    year: "2023",
    task: "CLS",
    mlModel: "Decision Trees",
    xaiMethod: "SHAP",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local",
    metrics: "F1-Score",
    problemType: "PM, BS, DS",
    mlStage: "Training",
    dataset: "Water Quality Monitoring Dataset (EPA)",
    inputType: "Num",
    outputType: "Num"
  },
  {
    domain: "Environment",
    author: "Gao et al. (2022)",
    year: "2021",
    task: "REG",
    mlModel: "CNN",
    xaiMethod: "Grad-CAM",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Specific",
    level: "Local",
    metrics: "Detection Rate",
    problemType: "BS, DS",
    mlStage: "Evaluation",
    dataset: "Solar Irradiance Dataset",
    inputType: "Num",
    outputType: "Img"
  },
  {
    domain: "Environment",
    author: "Huang et al. (2023)",
    year: "2022",
    task: "Analysis",
    mlModel: "Random Forest",
    xaiMethod: "SHAP",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local/Global",
    metrics: "Usability Metrics",
    problemType: "EM",
    mlStage: "Deployment",
    dataset: "Deforestation Satellite Imagery Dataset",
    inputType: "Img",
    outputType: "Cat"
  },
  {
    domain: "Environment",
    author: "Abdollahi and Pradhan (2023)",
    year: "2023",
    task: "CLS",
    mlModel: "Random Forest",
    xaiMethod: "SHAP",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local/Global",
    metrics: "Usability Metrics",
    problemType: "PM, BS, DS",
    mlStage: "Deploy",
    dataset: "Satellite Imagery Dataset",
    inputType: "Img",
    outputType: "Cat"
  },

  // Miscellaneous Domain (8 papers)
  {
    domain: "Miscellaneous",
    author: "Shashaani et al. (2024)",
    year: "2024",
    task: "Strategy Prediction",
    mlModel: "RL",
    xaiMethod: "SHAP",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Specific",
    level: "Local/Global",
    metrics: "Precision, Accuracy",
    problemType: "PR, PM",
    mlStage: "Training",
    dataset: "StarCraft II Dataset",
    inputType: "Num",
    outputType: "Num"
  },
  {
    domain: "Miscellaneous",
    author: "Fulton et al. (2020)",
    year: "2020",
    task: "CLS",
    mlModel: "RL",
    xaiMethod: "SHAP, LIME",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local",
    metrics: "Stability",
    problemType: "PM, BS",
    mlStage: "Training",
    dataset: "Chess Gameplay Dataset",
    inputType: "Num",
    outputType: "Num"
  },
  {
    domain: "Miscellaneous",
    author: "Tao et al. (2020)",
    year: "2020",
    task: "CLS",
    mlModel: "Neural Networks",
    xaiMethod: "Grad-CAM",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Specific",
    level: "Local",
    metrics: "Precision, Usability",
    problemType: "PM, BS",
    mlStage: "Training",
    dataset: "Dota 2 Gameplay Dataset",
    inputType: "Num",
    outputType: "Num"
  },
  {
    domain: "Miscellaneous",
    author: "Arora et al. (2023)",
    year: "2020",
    task: "CLS",
    mlModel: "CNN",
    xaiMethod: "Grad-CAM",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Specific",
    level: "Local",
    metrics: "Recall, Precision",
    problemType: "PM, BS",
    mlStage: "Training",
    dataset: "WikiArt Dataset",
    inputType: "Img",
    outputType: "Cat"
  },
  {
    domain: "Miscellaneous",
    author: "Bryan-kinns et al. (2023)",
    year: "2022",
    task: "Generate",
    mlModel: "Generative Adversarial Networks",
    xaiMethod: "Attention Mechanisms",
    xaiCategory: "SE-AI",
    timing: "Intrinsic",
    scope: "Specific",
    level: "Global",
    metrics: "Stability",
    problemType: "GA",
    mlStage: "Evaluation",
    dataset: "Generated Art Dataset",
    inputType: "Img",
    outputType: "Cat"
  },
  {
    domain: "Miscellaneous",
    author: "Bryan-Kinns et al. (2023)",
    year: "2022",
    task: "RECM",
    mlModel: "LSTM",
    xaiMethod: "SHAP, LIME",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local",
    metrics: "F1-Score",
    problemType: "PM, BS",
    mlStage: "Evaluation",
    dataset: "GTZAN Music Dataset",
    inputType: "Num",
    outputType: "Cat"
  },
  {
    domain: "Miscellaneous",
    author: "Ruiz et al. (2022)",
    year: "2021",
    task: "RECS",
    mlModel: "Collaborative Filtering",
    xaiMethod: "Attention Mechanisms",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Specific",
    level: "Global",
    metrics: "Usability Metrics",
    problemType: "RM, BS",
    mlStage: "Deployment",
    dataset: "MovieLens Dataset",
    inputType: "Num",
    outputType: "Cat"
  },
  {
    domain: "Miscellaneous",
    author: "Wood et al. (2024)",
    year: "2020",
    task: "ANOM",
    mlModel: "Random Forest",
    xaiMethod: "SHAP",
    xaiCategory: "FA",
    timing: "Post-hoc",
    scope: "Agnostic",
    level: "Local",
    metrics: "Accuracy, Stability",
    problemType: "PM, BS, DS",
    mlStage: "Evaluation",
    dataset: "Military Surveillance Data",
    inputType: "Num",
    outputType: "Num"
  }
];